# Generated by Django 4.2.1 on 2023-06-29 02:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_mandato_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="mandato",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mandato",
            name="monto",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="mandato",
            name="numero_tarjeta",
            field=models.CharField(
                max_length=16,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(16)],
            ),
        ),
    ]
