# Generated by Django 4.2.1 on 2023-06-29 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_mandato_start_date_alter_mandato_monto_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Residente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_apellido", models.CharField(max_length=100)),
                ("rut", models.CharField(max_length=20)),
                ("nacionalidad", models.CharField(default="Chileno/a", max_length=50)),
                ("fecha_nacimiento", models.DateField()),
                (
                    "estado_civil",
                    models.CharField(
                        choices=[
                            ("S", "Soltero/a"),
                            ("C", "Casado/a"),
                            ("V", "Viudo/a"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "genero",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino")], max_length=1
                    ),
                ),
                ("direccion", models.CharField(max_length=200)),
                ("comuna", models.CharField(max_length=100)),
                ("celular", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Fichamedica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("presion_arterial", models.CharField(max_length=20)),
                ("alergias", models.TextField()),
                ("condiciones_medicas", models.TextField()),
                ("medicamentos", models.TextField()),
                (
                    "residente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.residente",
                    ),
                ),
            ],
        ),
    ]
