# Generated by Django 4.2.1 on 2023-06-29 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_residente_en_hogar_alter_mandato_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="residente",
            name="admitido",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="residente",
            name="fecha_admision",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="residente",
            name="fecha_egreso",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Ingreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_admision", models.DateField()),
                (
                    "residente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.residente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Egreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_egreso", models.DateField()),
                (
                    "residente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.residente",
                    ),
                ),
            ],
        ),
    ]
