# Generated by Django 4.2.1 on 2023-06-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_remove_residente_admitido_residente_estado_en_hogar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="residente",
            name="en_hogar",
        ),
        migrations.AlterField(
            model_name="residente",
            name="fecha_admision",
            field=models.DateField(blank=True, null=True),
        ),
    ]
