# Generated by Django 4.2.1 on 2023-07-10 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_residente_en_hogar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DosisMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.CharField(max_length=100)),
                ('hora_administracion', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('compuesto', models.CharField(max_length=100)),
                ('dosis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlanMedicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('medicamentos', models.ManyToManyField(through='users.DosisMedicamento', to='users.medicamento')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.residente')),
            ],
        ),
        migrations.AddField(
            model_name='dosismedicamento',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.medicamento'),
        ),
        migrations.AddField(
            model_name='dosismedicamento',
            name='plan_medicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.planmedicacion'),
        ),
    ]
