# Generated by Django 4.2.1 on 2023-07-10 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_dosismedicamento_medicamento_planmedicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planmedicacion',
            name='residente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.residente'),
        ),
    ]
