# Generated by Django 4.2.1 on 2023-07-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_dosis_dosismedicamento_dosis_diarias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingreso',
            name='residente',
        ),
        migrations.RemoveField(
            model_name='fichamedica',
            name='condiciones_medicas',
        ),
        migrations.RemoveField(
            model_name='fichamedica',
            name='medicamentos',
        ),
        migrations.RemoveField(
            model_name='fichamedica',
            name='presion_arterial',
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='cirugias_previas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='cuidado_especializado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='enfermedades_cronicas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='necesidades_especificas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='restricciones_dieteticas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='vacunas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='alergias',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Egreso',
        ),
        migrations.DeleteModel(
            name='Ingreso',
        ),
    ]
