# Generated by Django 4.2.1 on 2023-06-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mandato",
            name="modalidad",
            field=models.CharField(default="Mensual", max_length=50),
        ),
        migrations.AlterField(
            model_name="mandato",
            name="casa_comercial",
            field=models.CharField(
                choices=[
                    ("AbcVisa", "AbcVisa"),
                    ("Falabella", "Falabella"),
                    ("Hites", "Hites"),
                    ("La Polar", "La Polar"),
                    ("Paris", "Paris"),
                    ("Ripley", "Ripley"),
                ],
                max_length=50,
            ),
        ),
    ]
