# Generated by Django 4.2.1 on 2023-06-22 21:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_mandato_modalidad_alter_mandato_casa_comercial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Mandato",
        ),
    ]
